
###
GET https://v3.football.api-sports.io/status
x-rapidapi-host:v3.football.api-sports.io
x-rapidapi-key:3a263e195713aaef25d730cc3cbca2f9

###
GET http://localhost:8080/taborets/all
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/taborets/5
Content-Type: application/json
Accept: application/json